server: https://chat.service.toshi.org
token_ethereum_service_url: https://ethereum.service.toshi.org
token_id_service_url: https://identity.service.toshi.org
token_exchange_service_url: https://exchange.service.toshi.org
redis:
  envKey: REDIS_URL
  timeout: 2000
storage:
  envKey: DATABASE_URL
  sslmode: require
